-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 12:06:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CustomerOrders
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CustomerOrders` ;

-- -----------------------------------------------------
-- Schema CustomerOrders
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CustomerOrders` DEFAULT CHARACTER SET utf8 ;
USE `CustomerOrders` ;

-- -----------------------------------------------------
-- Table `CustomerOrders`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerOrders`.`Customers` ;

CREATE TABLE IF NOT EXISTS `CustomerOrders`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CustomerID`),
  UNIQUE INDEX `CustomerID_UNIQUE` (`CustomerID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerOrders`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerOrders`.`Orders` ;

CREATE TABLE IF NOT EXISTS `CustomerOrders`.`Orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE INDEX `idOrders_UNIQUE` (`OrderID` ASC),
  INDEX `fk_customerorders_idx` (`CustomerID` ASC),
  CONSTRAINT `fk_customerorders`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `CustomerOrders`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerOrders`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerOrders`.`Address` ;

CREATE TABLE IF NOT EXISTS `CustomerOrders`.`Address` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AddressID`),
  UNIQUE INDEX `AdressID_UNIQUE` (`AddressID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerOrders`.`CustomerAddressXref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerOrders`.`CustomerAddressXref` ;

CREATE TABLE IF NOT EXISTS `CustomerOrders`.`CustomerAddressXref` (
  `CustomerID` INT NOT NULL,
  `AddressID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`, `AddressID`),
  UNIQUE INDEX `CustomerID_UNIQUE` (`CustomerID` ASC),
  UNIQUE INDEX `AddressID_UNIQUE` (`AddressID` ASC),
  CONSTRAINT `fkCustomerAddress`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `CustomerOrders`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAddressCustomer`
    FOREIGN KEY (`AddressID`)
    REFERENCES `CustomerOrders`.`Address` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
